use miette::Diagnostic;
use refs_cli::lock::Lock;

const LOCK: &str = r#"# Generated by refs. Do not edit.
version = 1
generator = "refs 0.1.0"
config_hash = "sha256:abc"

[[repo]]
id = "solid"
source = "git"
url = "https://github.com/solidjs/solid"
ref = "next"
sha = "1a2b3c4d5e6f0000000000000000000000000000"
paths = ["packages", "documentation"]

[[repo]]
id = "zed"
source = "git"
url = "https://github.com/zed-industries/zed"
ref = "HEAD"
sha = "2b3c4d5e6f700000000000000000000000000000"
branch = "main"
"#;

#[test]
fn a_lock_round_trips_byte_for_byte() {
    let lock = Lock::parse(LOCK).unwrap();
    assert_eq!(lock.to_toml(), LOCK);
}

#[test]
fn entries_are_written_sorted_by_id() {
    let mut lock = Lock::parse(LOCK).unwrap();
    lock.repo.reverse();
    assert_eq!(lock.to_toml(), LOCK);
}

#[test]
fn an_entry_without_source_is_rejected() {
    let text = LOCK.replacen("source = \"git\"\n", "", 1);
    let err = Lock::parse(&text).unwrap_err();
    assert_eq!(err.code().unwrap().to_string(), "refs::lock::invalid");
}

#[test]
fn an_unknown_source_kind_is_rejected() {
    let text = LOCK.replacen("source = \"git\"", "source = \"tarball\"", 1);
    let err = Lock::parse(&text).unwrap_err();
    assert_eq!(err.code().unwrap().to_string(), "refs::lock::invalid");
}

mod config_hash {
    use refs_cli::active::active;
    use refs_cli::config::parse;
    use refs_cli::lock::config_hash;

    const BASE: &str = r#"
[groups.ui]
name = "UI"
description = "front end"

[repos.solid]
url = "https://github.com/solidjs/solid"
ref = "next"
paths = ["packages", "documentation"]
group = "ui"
description = "signals"
packages = ["solid-js"]
start = ["README.md"]

[repos.zed]
url = "https://github.com/zed-industries/zed"
"#;

    fn hash(text: &str) -> String {
        config_hash(&active(&parse(text).unwrap()))
    }

    fn changed(from: &str, to: &str) -> bool {
        hash(BASE) != hash(&BASE.replacen(from, to, 1))
    }

    #[test]
    fn it_is_a_sha256_digest() {
        let h = hash(BASE);
        assert!(h.starts_with("sha256:"));
        assert_eq!(h.len(), "sha256:".len() + 64);
    }

    #[test]
    fn it_changes_with_url_ref_paths_and_ids() {
        assert!(changed("zed-industries/zed", "zed-industries/zed2"));
        assert!(changed("\"next\"", "\"main\""));
        assert!(changed("\"documentation\"", "\"docs\""));
        assert!(changed("[repos.zed]", "[repos.zed2]"));
    }

    #[test]
    fn it_changes_with_the_active_set() {
        let disabled = BASE.replacen("[repos.zed]", "[repos.zed]\nenabled = false", 1);
        assert_ne!(hash(BASE), hash(&disabled));
    }

    #[test]
    fn it_ignores_display_fields_and_grouping() {
        assert!(!changed(
            "description = \"front end\"",
            "description = \"other\""
        ));
        assert!(!changed("name = \"UI\"", "name = \"User interface\""));
        assert!(!changed("signals", "reactivity"));
        assert!(!changed("[\"solid-js\"]", "[\"solid-js\", \"x\"]"));
        assert!(!changed("[\"README.md\"]", "[\"LICENSE\"]"));
        assert!(!changed("group = \"ui\"\n", ""));
    }

    #[test]
    fn an_absent_ref_means_head() {
        let explicit = BASE.replacen("zed\"\n", "zed\"\nref = \"HEAD\"\n", 1);
        assert_eq!(hash(BASE), hash(&explicit));
    }

    #[test]
    fn config_order_does_not_matter() {
        let reordered = r#"
[repos.zed]
url = "https://github.com/zed-industries/zed"

[repos.solid]
url = "https://github.com/solidjs/solid"
ref = "next"
paths = ["packages", "documentation"]
"#;
        assert_eq!(hash(BASE), hash(reordered));
    }
}

mod write {
    use super::*;

    #[test]
    fn writing_replaces_the_file_and_leaves_nothing_behind() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("refs.lock");
        std::fs::write(&path, "old").unwrap();

        let lock = Lock::parse(LOCK).unwrap();
        lock.write(&path).unwrap();

        assert_eq!(std::fs::read_to_string(&path).unwrap(), LOCK);
        let names: Vec<_> = std::fs::read_dir(dir.path())
            .unwrap()
            .map(|e| e.unwrap().file_name())
            .collect();
        assert_eq!(names, ["refs.lock"]);
    }

    #[test]
    fn a_failed_write_is_reported_with_a_code() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("missing").join("refs.lock");

        let err = Lock::parse(LOCK).unwrap().write(&path).unwrap_err();
        assert_eq!(err.code().unwrap().to_string(), "refs::lock::write_failed");
    }
}

mod untrusted_lock {
    use super::*;

    fn code(text: &str) -> String {
        Lock::parse(text).unwrap_err().code().unwrap().to_string()
    }

    #[test]
    fn a_short_sha_is_rejected() {
        let text = LOCK.replacen("1a2b3c4d5e6f0000000000000000000000000000", "1a2b3c", 1);
        assert_eq!(code(&text), "refs::lock::invalid");
    }

    #[test]
    fn a_non_hex_sha_is_rejected() {
        let text = LOCK.replacen(
            "1a2b3c4d5e6f0000000000000000000000000000",
            &"é".repeat(40),
            1,
        );
        assert_eq!(code(&text), "refs::lock::invalid");
    }

    #[test]
    fn an_unknown_version_is_rejected() {
        let text = LOCK.replacen("version = 1", "version = 2", 1);
        assert_eq!(code(&text), "refs::lock::invalid");
    }
}
