use miette::Diagnostic;
use refs_cli::lock::Lock;

const LOCK: &str = r#"# Generated by refs. Do not edit.
version = 1

[[repo]]
id = "solid"
source = "git"
url = "https://github.com/solidjs/solid"
ref = "next"
sha = "1a2b3c4d5e6f0000000000000000000000000000"

[[repo]]
id = "zed"
source = "git"
url = "https://github.com/zed-industries/zed"
ref = "HEAD"
sha = "2b3c4d5e6f700000000000000000000000000000"
branch = "main"
"#;

#[test]
fn a_lock_round_trips_byte_for_byte() {
    let lock = Lock::parse(LOCK).unwrap();
    assert_eq!(lock.to_toml(), LOCK);
}

#[test]
fn entries_are_written_sorted_by_id() {
    let mut lock = Lock::parse(LOCK).unwrap();
    lock.repo.reverse();
    assert_eq!(lock.to_toml(), LOCK);
}

#[test]
fn an_entry_without_source_is_rejected() {
    let text = LOCK.replacen("source = \"git\"\n", "", 1);
    let err = Lock::parse(&text).unwrap_err();
    assert_eq!(err.code().unwrap().to_string(), "refs::lock::invalid");
}

#[test]
fn an_unknown_source_kind_is_rejected() {
    let text = LOCK.replacen("source = \"git\"", "source = \"tarball\"", 1);
    let err = Lock::parse(&text).unwrap_err();
    assert_eq!(err.code().unwrap().to_string(), "refs::lock::invalid");
}

mod write {
    use super::*;

    #[test]
    fn writing_replaces_the_file_and_leaves_nothing_behind() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("refs.lock");
        std::fs::write(&path, "old").unwrap();

        let lock = Lock::parse(LOCK).unwrap();
        lock.write(&path).unwrap();

        assert_eq!(std::fs::read_to_string(&path).unwrap(), LOCK);
        let names: Vec<_> = std::fs::read_dir(dir.path())
            .unwrap()
            .map(|e| e.unwrap().file_name())
            .collect();
        assert_eq!(names, ["refs.lock"]);
    }

    #[test]
    fn a_failed_write_is_reported_with_a_code() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("missing").join("refs.lock");

        let err = Lock::parse(LOCK).unwrap().write(&path).unwrap_err();
        assert_eq!(err.code().unwrap().to_string(), "refs::lock::write_failed");
    }
}

mod untrusted_lock {
    use super::*;

    fn code(text: &str) -> String {
        Lock::parse(text).unwrap_err().code().unwrap().to_string()
    }

    #[test]
    fn a_short_sha_is_rejected() {
        let text = LOCK.replacen("1a2b3c4d5e6f0000000000000000000000000000", "1a2b3c", 1);
        assert_eq!(code(&text), "refs::lock::invalid");
    }

    #[test]
    fn a_non_hex_sha_is_rejected() {
        let text = LOCK.replacen(
            "1a2b3c4d5e6f0000000000000000000000000000",
            &"é".repeat(40),
            1,
        );
        assert_eq!(code(&text), "refs::lock::invalid");
    }

    #[test]
    fn an_unknown_version_is_rejected() {
        let text = LOCK.replacen("version = 1", "version = 2", 1);
        assert_eq!(code(&text), "refs::lock::invalid");
    }
}

mod read {
    use super::*;

    #[test]
    fn a_missing_lock_is_none() {
        let dir = tempfile::tempdir().unwrap();

        assert_eq!(Lock::read(&Lock::path(dir.path())).unwrap(), None);
    }

    #[test]
    fn the_lock_lives_in_refs_lock_at_the_project_root() {
        let dir = tempfile::tempdir().unwrap();
        let lock = Lock::parse(LOCK).unwrap();
        lock.write(&Lock::path(dir.path())).unwrap();

        assert!(dir.path().join("refs.lock").is_file());
        assert_eq!(Lock::read(&Lock::path(dir.path())).unwrap(), Some(lock));
    }

    #[test]
    fn an_invalid_lock_is_reported_not_ignored() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(Lock::path(dir.path()), "version = 2\n").unwrap();

        let err = Lock::read(&Lock::path(dir.path())).unwrap_err();
        assert_eq!(err.code().unwrap().to_string(), "refs::lock::invalid");
    }

    #[test]
    fn an_unreadable_lock_is_reported_with_a_code() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::create_dir(Lock::path(dir.path())).unwrap();

        let err = Lock::read(&Lock::path(dir.path())).unwrap_err();
        assert_eq!(err.code().unwrap().to_string(), "refs::lock::read_failed");
    }
}

#[test]
fn a_lock_that_still_records_paths_is_read_and_loses_them_on_write() {
    let old = LOCK.replace(
        "sha = \"1a2b3c4d5e6f0000000000000000000000000000\"\n",
        "sha = \"1a2b3c4d5e6f0000000000000000000000000000\"\npaths = [\"packages\"]\n",
    );
    let lock = Lock::parse(&old).unwrap();
    assert_eq!(lock.to_toml(), LOCK);
}
