//! The versions a Package lockfile says a project uses, from trimmed real lockfiles.

use refs_cli::registry::lockfile::{Format, Used, used_versions};

fn used(version: &str, direct: bool) -> Used {
    Used {
        version: version.to_owned(),
        direct,
    }
}

mod cargo {
    use super::*;

    const LOCK: &str = r#"
# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "app"
version = "0.1.0"
dependencies = [
 "foo-bar",
 "serde",
 "tokio 1.40.0",
]

[[package]]
name = "foo-bar"
version = "0.3.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "aa"

[[package]]
name = "mine"
version = "0.2.0"
source = "git+https://github.com/me/mine?rev=abc#abc"

[[package]]
name = "serde"
version = "1.0.200"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "bb"
dependencies = ["serde_derive"]

[[package]]
name = "serde_derive"
version = "1.0.200"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "cc"

[[package]]
name = "tokio"
version = "1.39.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "dd"

[[package]]
name = "tokio"
version = "1.40.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "ee"
"#;

    fn of(name: &str) -> Vec<Used> {
        used_versions(Format::CargoLock, name, LOCK).unwrap()
    }

    #[test]
    fn a_dependency_of_the_project_is_direct() {
        assert_eq!(of("serde"), [used("1.0.200", true)]);
    }

    #[test]
    fn a_dependency_of_a_dependency_is_not() {
        assert_eq!(of("serde_derive"), [used("1.0.200", false)]);
    }

    #[test]
    fn of_several_versions_the_one_the_project_names_is_direct() {
        assert_eq!(of("tokio"), [used("1.39.0", false), used("1.40.0", true)]);
    }

    #[test]
    fn a_dash_and_an_underscore_are_the_same_in_a_crate_name() {
        assert_eq!(of("foo_bar"), [used("0.3.0", true)]);
    }

    #[test]
    fn a_crate_from_git_or_the_project_itself_is_not_a_registry_version() {
        assert_eq!(of("mine"), []);
        assert_eq!(of("app"), []);
    }

    #[test]
    fn a_crate_not_in_the_lockfile_has_no_version() {
        assert_eq!(of("rand"), []);
    }

    #[test]
    fn a_lockfile_that_is_not_toml_is_an_error() {
        assert!(used_versions(Format::CargoLock, "serde", "{ not toml").is_err());
    }
}

mod package_lock {
    use super::*;

    const V3: &str = r#"{
  "name": "web",
  "lockfileVersion": 3,
  "packages": {
    "": {
      "name": "web",
      "dependencies": { "react": "^18.2.0", "lodash-alias": "npm:lodash@^4" },
      "devDependencies": { "@babel/core": "^7.23.0" }
    },
    "node_modules/@babel/core": { "version": "7.23.2", "resolved": "https://registry.npmjs.org/@babel/core/-/core-7.23.2.tgz" },
    "node_modules/react": { "version": "18.2.0", "resolved": "https://registry.npmjs.org/react/-/react-18.2.0.tgz" },
    "node_modules/lodash-alias": { "name": "lodash", "version": "4.17.21", "resolved": "https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz" },
    "node_modules/ms": { "version": "2.1.3", "resolved": "https://registry.npmjs.org/ms/-/ms-2.1.3.tgz" },
    "node_modules/debug/node_modules/ms": { "version": "2.0.0", "resolved": "https://registry.npmjs.org/ms/-/ms-2.0.0.tgz" },
    "node_modules/local": { "resolved": "packages/local", "link": true },
    "node_modules/fromgit": { "version": "1.0.0", "resolved": "git+ssh://git@github.com/me/fromgit.git#abc" },
    "packages/local": { "version": "0.0.1" }
  }
}"#;

    const V1: &str = r#"{
  "lockfileVersion": 1,
  "dependencies": {
    "ms": {
      "version": "2.1.3",
      "resolved": "https://registry.npmjs.org/ms/-/ms-2.1.3.tgz"
    },
    "debug": {
      "version": "4.3.4",
      "resolved": "https://registry.npmjs.org/debug/-/debug-4.3.4.tgz",
      "requires": { "ms": "2.1.2" },
      "dependencies": {
        "ms": { "version": "2.1.2", "resolved": "https://registry.npmjs.org/ms/-/ms-2.1.2.tgz" }
      }
    }
  }
}"#;

    fn of3(name: &str) -> Vec<Used> {
        used_versions(Format::PackageLock, name, V3).unwrap()
    }

    #[test]
    fn a_package_the_project_names_is_direct() {
        assert_eq!(of3("react"), [used("18.2.0", true)]);
        assert_eq!(of3("@babel/core"), [used("7.23.2", true)]);
    }

    #[test]
    fn a_hoisted_package_nobody_in_the_project_names_is_not_direct() {
        assert_eq!(of3("ms"), [used("2.0.0", false), used("2.1.3", false)]);
    }

    #[test]
    fn an_alias_is_found_by_the_real_name() {
        assert_eq!(of3("lodash"), [used("4.17.21", true)]);
        assert_eq!(of3("lodash-alias"), []);
    }

    #[test]
    fn a_link_a_git_package_and_a_workspace_are_not_registry_versions() {
        assert_eq!(of3("local"), []);
        assert_eq!(of3("fromgit"), []);
    }

    #[test]
    fn version_1_lists_every_version_and_marks_none_direct() {
        assert_eq!(
            used_versions(Format::PackageLock, "ms", V1).unwrap(),
            [used("2.1.2", false), used("2.1.3", false)]
        );
        assert_eq!(
            used_versions(Format::PackageLock, "debug", V1).unwrap(),
            [used("4.3.4", false)]
        );
    }

    #[test]
    fn a_lockfile_that_is_not_json_is_an_error() {
        assert!(used_versions(Format::PackageLock, "react", "nope").is_err());
    }
}
