use miette::Diagnostic;
use refs_cli::active::active;
use refs_cli::config::parse;
use refs_cli::lock::{Lock, LockedRepo};
use refs_cli::render::render;
use refs_cli::source::Pin;

const SHA: &str = "ee49b3e0123456789012345678901234567890ab";

/// A lock pinning each `(id, ref, branch)` to `SHA`.
fn lock(repos: &[(&str, &str, Option<&str>)]) -> Lock {
    Lock {
        version: 1,
        repo: repos
            .iter()
            .map(|(id, git_ref, branch)| LockedRepo {
                id: id.to_string(),
                pin: Pin::git("https://example.com/o/r", git_ref, SHA, *branch),
            })
            .collect(),
    }
}

/// Render the `config` text against `lock`, into the default references directory.
fn block(config: &str, lock: &Lock) -> String {
    let config = parse(config).unwrap();
    render(&active(&config), lock, config.settings.references_dir()).unwrap()
}

#[test]
fn one_repo_renders_the_whole_block() {
    let config = r#"
[repos.solid]
url = "https://example.com/o/r"
ref = "next"
description = "Solid core"
packages = ["solid-js", "@solidjs/web"]
start = ["MIGRATION.md"]
"#;
    let expected = "\
<!-- BEGIN:refs -->

## Reference repos

```text
Source and docs for some dependencies are checked out read-only in `.references/`, pinned in `refs.lock`. They can be newer than your training data. Prefer retrieval-led reasoning over pre-training-led reasoning for these libraries: read the relevant files before writing code that uses them. Look up an imported API in a repo whose `Packages:` lists the package it's imported from (e.g. imports from `solid-js` → `.references/solid`); APIs with the same name can behave differently in different packages.

`.references/` is excluded from default search. To search it, pass the path explicitly, e.g. `.references/solid`. Don't edit anything in `.references/`; it is regenerated by `refs sync`. If `.references/` is missing, tell the user to run `refs sync`.
```

### Ungrouped

```text
[solid @ next ee49b3e] Solid core. Packages: solid-js, @solidjs/web. Start: MIGRATION.md.
```

<!-- END:refs -->";
    assert_eq!(block(config, &lock(&[("solid", "next", None)])), expected);
}

/// The lines of the block between the first fence and the last, to keep the goldens
/// about what varies. The preamble is pinned by `one_repo_renders_the_whole_block`.
fn body(block: &str) -> &str {
    let start = block.find("### ").unwrap_or(block.len());
    &block[start..block.len() - "<!-- END:refs -->".len()]
}

#[test]
fn a_repo_with_no_optional_fields_is_just_its_id_ref_and_sha() {
    let config = "[repos.a]\nurl = \"https://example.com/o/r\"\nref = \"v1\"\n";
    insta::assert_snapshot!(body(&block(config, &lock(&[("a", "v1", None)]))));
}

#[test]
fn a_sha_ref_is_shown_once() {
    let config = format!("[repos.a]\nurl = \"https://example.com/o/r\"\nref = \"{SHA}\"\n");
    insta::assert_snapshot!(body(&block(&config, &lock(&[("a", SHA, None)]))));
}

#[test]
fn head_shows_the_locked_branch_or_stays_head() {
    let config = "[repos.a]\nurl = \"https://example.com/o/r\"\n";
    let with = block(config, &lock(&[("a", "HEAD", Some("main"))]));
    let without = block(config, &lock(&[("a", "HEAD", None)]));
    assert!(with.contains("[a @ main ee49b3e]"), "{with}");
    assert!(without.contains("[a @ HEAD ee49b3e]"), "{without}");
}

#[test]
fn only_a_head_ref_shows_the_branch() {
    let config = "[repos.a]\nurl = \"https://example.com/o/r\"\nref = \"v1\"\n";
    let text = block(config, &lock(&[("a", "v1", Some("main"))]));
    assert!(text.contains("[a @ v1 ee49b3e]"), "{text}");
}

#[test]
fn only_a_full_sha_collapses_to_the_short_id() {
    // an abbreviated sha is not a valid ref, but a tag can look like one
    let config = "[repos.a]\nurl = \"https://example.com/o/r\"\nref = \"ee49b3e\"\n";
    let text = block(config, &lock(&[("a", "ee49b3e", None)]));
    assert!(text.contains("[a @ ee49b3e ee49b3e]"), "{text}");
}

#[test]
fn a_description_that_ends_in_a_period_does_not_get_a_second() {
    let config = "[repos.a]\nurl = \"https://example.com/o/r\"\ndescription = \"Done.\"\n";
    let text = block(config, &lock(&[("a", "HEAD", None)]));
    assert!(text.contains("[a @ HEAD ee49b3e] Done.\n"), "{text}");
}

#[test]
fn groups_render_in_order_with_their_description_inside_the_fence() {
    let config = r#"
[groups.later]
name = "Later (v2): x/y + z & more"

[groups.first]
name = "First"
description = "When to look here."

[groups.empty]
name = "Empty"

[repos.u]
url = "https://example.com/o/u"

[repos.b]
url = "https://example.com/o/b"
group = "first"
packages = ["bee"]

[repos.a]
url = "https://example.com/o/a"
group = "later"
description = "Alpha"
"#;
    let lock = lock(&[("u", "HEAD", None), ("b", "main", None), ("a", "v2", None)]);
    insta::assert_snapshot!(body(&block(config, &lock)));
}

#[test]
fn without_packages_the_lookup_sentence_is_left_out() {
    let config = "[repos.a]\nurl = \"https://example.com/o/r\"\n";
    let text = block(config, &lock(&[("a", "HEAD", None)]));
    assert!(!text.contains("Packages:"), "{text}");
    insta::assert_snapshot!(text);
}

#[test]
fn references_dir_is_substituted_into_the_prose() {
    let config = "[settings]\nreferences_dir = \"vendor/refs\"\n\n[repos.a]\nurl = \"https://example.com/o/r\"\npackages = [\"p\"]\n";
    let text = block(config, &lock(&[("a", "HEAD", None)]));
    assert!(!text.contains(".references"), "{text}");
    insta::assert_snapshot!(text);
}

#[test]
fn a_repo_the_lock_does_not_cover_is_an_error_naming_it() {
    let config = parse("[repos.a]\nurl = \"https://example.com/o/r\"\n[repos.b]\nurl = \"https://example.com/o/r\"\n").unwrap();
    let err = render(
        &active(&config),
        &lock(&[("a", "HEAD", None)]),
        ".references",
    )
    .unwrap_err();
    assert_eq!(err.ids, ["b"]);
    assert_eq!(err.code().unwrap().to_string(), "refs::render::not_locked");
}

#[test]
fn rendering_twice_gives_the_same_bytes() {
    let config = "[repos.a]\nurl = \"https://example.com/o/r\"\npackages = [\"p\"]\n";
    let lock = lock(&[("a", "HEAD", Some("main"))]);
    assert_eq!(block(config, &lock), block(config, &lock));
}

/// A block that exercises everything the formatters could object to.
fn rich_block() -> String {
    let config = r#"
[groups.g]
name = "Rust (std) + C/C++ & more, v1: x-y/z. Ünïcode 7"
description = "Newer than your training data; many APIs differ. Use `code`, *stars*, _under_, | pipes | and # hashes."

[repos.solid]
url = "https://example.com/o/r"
group = "g"
ref = "next"
description = "Solid 2.0 core | table-ish * star _ under # hash"
packages = ["solid-js", "@solidjs/web", "@scope/pkg-x"]
start = ["documentation/solid-2.0/MIGRATION.md", "a_b/c*d.md"]

[repos.plain]
url = "https://example.com/o/p"
"#;
    block(
        config,
        &lock(&[("solid", "next", None), ("plain", "HEAD", Some("main"))]),
    )
}

/// Formatter stability (spec §8.1): `sync --check` must not fight `fmt --check`. Each tool
/// runs through `npx`; one that cannot be started (no `npx`, no network) skips its test.
mod formatters {
    use std::process::Command;

    use super::rich_block;

    /// One formatter in one mode: the files it needs, and the command that rewrites
    /// `AGENTS.md` in place.
    struct Run {
        tool: &'static str,
        files: &'static [(&'static str, &'static str)],
        args: &'static [&'static str],
    }

    fn npx(args: &[&str], dir: &std::path::Path) -> Option<std::process::Output> {
        Command::new("npx")
            .arg("--yes")
            .args(args)
            .current_dir(dir)
            .output()
            .ok()
    }

    fn assert_unchanged(run: Run) {
        let dir = tempfile::tempdir().unwrap();
        if !npx(&[run.tool, "--version"], dir.path()).is_some_and(|o| o.status.success()) {
            eprintln!("skipping: `npx {}` is not available", run.tool);
            return;
        }
        let original = format!("# Notes\n\nSome text.\n\n{}\n\nMore text.\n", rich_block());
        for (name, content) in run.files {
            std::fs::write(dir.path().join(name), content).unwrap();
        }
        let file = dir.path().join("AGENTS.md");
        std::fs::write(&file, &original).unwrap();
        let mut args = vec![run.tool];
        args.extend(run.args);
        let out = npx(&args, dir.path()).expect("npx ran a moment ago");
        assert!(
            out.status.success(),
            "{}",
            String::from_utf8_lossy(&out.stderr)
        );
        let formatted = std::fs::read_to_string(&file).unwrap();
        assert_eq!(
            formatted, original,
            "{} {:?} rewrote the block",
            run.tool, run.args
        );
    }

    #[test]
    fn oxfmt_leaves_the_block_alone() {
        for config in ["{}", r#"{"proseWrap": "always"}"#] {
            let files: &'static [(&str, &str)] = Box::leak(Box::new([(".oxfmtrc.json", config)]));
            assert_unchanged(Run {
                tool: "oxfmt",
                files,
                args: &["AGENTS.md"],
            });
        }
    }

    #[test]
    fn prettier_leaves_the_block_alone() {
        for wrap in ["preserve", "always"] {
            let args: &'static [&str] =
                Box::leak(Box::new(["--write", "--prose-wrap", wrap, "AGENTS.md"]));
            assert_unchanged(Run {
                tool: "prettier",
                files: &[],
                args,
            });
        }
    }

    #[test]
    fn dprint_leaves_the_block_alone() {
        for wrap in ["maintain", "always"] {
            let config = format!(
                r#"{{"plugins": ["npm:@dprint/markdown@0.25.0"], "markdown": {{"textWrap": "{wrap}"}}}}"#
            );
            let files: &'static [(&str, &str)] = Box::leak(Box::new([(
                "dprint.json",
                &*Box::leak(config.into_boxed_str()),
            )]));
            assert_unchanged(Run {
                tool: "dprint",
                files,
                args: &["fmt", "AGENTS.md"],
            });
        }
    }
}
