//! `refs.lock`: what each active Repo resolved to. Serialisation only; no decisions.

use std::path::Path;

use serde::{Deserialize, Serialize};

use crate::diagnostic::LockError;
use crate::source::Pin;

const VERSION: u32 = 1;
const HEADER: &str = "# Generated by refs. Do not edit.\n";

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Lock {
    pub version: u32,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub repo: Vec<LockedRepo>,
}

/// One locked Repo. The `source` tag and its fields live in the `Pin`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct LockedRepo {
    pub id: String,
    #[serde(flatten)]
    pub pin: Pin,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub paths: Vec<String>,
}

impl Lock {
    pub fn parse(text: &str) -> Result<Lock, LockError> {
        let invalid = |message: String| LockError::Invalid { message };
        let lock: Lock = toml::from_str(text).map_err(|e| invalid(e.message().to_string()))?;
        if lock.version != VERSION {
            return Err(invalid(format!("unsupported version {}", lock.version)));
        }
        if let Some(bad) = lock.repo.iter().find(|e| !e.pin.is_well_formed()) {
            return Err(invalid(format!(
                "entry `{}` has a malformed commit id",
                bad.id
            )));
        }
        Ok(lock)
    }

    /// Stable text: entries sorted by id.
    pub fn to_toml(&self) -> String {
        let mut sorted = self.clone();
        sorted.repo.sort_by(|a, b| a.id.cmp(&b.id));
        let body = toml::to_string(&sorted).expect("a lock is always serialisable");
        format!("{HEADER}{body}")
    }

    /// Write atomically, so a reader never sees a partial lock.
    pub fn write(&self, path: &Path) -> Result<(), LockError> {
        crate::atomic::write(path, &self.to_toml()).map_err(|source| LockError::Write {
            path: path.display().to_string(),
            source,
        })
    }
}
