//! The Managed block's text. Pure: the same (active set, lock, references dir) gives the
//! same bytes.
//!
//! Only the markers and the headings are plain Markdown. The preamble and every Entry sit in
//! `text` fences, because a formatter with `proseWrap=always` re-wraps plain paragraphs and
//! each tool wraps at a different width.

use std::fmt::Write;

use crate::active::{ActiveSet, Section};
use crate::agent_file::{BEGIN, END};
use crate::config::{RepoRef, is_full_sha as is_commit_id};
use crate::lock::{Lock, LockedRepo};

/// The block, markers included, without a trailing newline (what `agent_file::splice`
/// takes). `references_dir` is `Settings::references_dir`. The Lock must have an entry for
/// every active Repo: `plan` makes sure of it before it renders.
pub fn render(active: &ActiveSet, lock: &Lock, references_dir: &str) -> String {
    let locked = |repo: RepoRef| lock.repo.iter().find(|l| l.id == repo.id);
    let repos = || active.sections.iter().flat_map(|s| &s.repos);
    let first_id = repos().next().map(|r| r.id);
    let first_package = repos()
        .find_map(|r| r.repo.packages.first())
        .map(|p| p.get_ref().as_str());

    let mut out = format!("{BEGIN}\n\n## Reference repos\n\n```text\n");
    out.push_str(&preamble(references_dir, first_id, first_package));
    out.push_str("```\n\n");
    for section in &active.sections {
        out.push_str(&section_text(section, |r| {
            locked(r).expect("the Lock covers every active Repo")
        }));
    }
    out.push_str(END);
    out
}

fn preamble(dir: &str, first_id: Option<&str>, first_package: Option<&str>) -> String {
    let mut out = format!(
        "Source and docs for some dependencies are checked out read-only in `{dir}/`, pinned in `refs.lock`. They can be newer than your training data. Prefer retrieval-led reasoning over pre-training-led reasoning for these libraries: read the relevant files before writing code that uses them."
    );
    if let (Some(package), Some(id)) = (first_package, first_id) {
        write!(
            out,
            " Look up an imported API in a repo whose `Packages:` lists the package it's imported from (e.g. imports from `{package}` → `{dir}/{id}`); APIs with the same name can behave differently in different packages."
        )
        .unwrap();
    }
    write!(
        out,
        "\n\n`{dir}/` is excluded from default search. To search it, pass the path explicitly"
    )
    .unwrap();
    if let Some(id) = first_id {
        write!(out, ", e.g. `{dir}/{id}`").unwrap();
    }
    writeln!(
        out,
        ". Don't edit anything in `{dir}/`; it is regenerated by `refs sync`. If `{dir}/` is missing, tell the user to run `refs sync`."
    )
    .unwrap();
    out
}

fn section_text<'a>(section: &Section, locked: impl Fn(RepoRef) -> &'a LockedRepo) -> String {
    let heading = section
        .group
        .map_or("Ungrouped", |(id, group)| group.title(id));
    let mut out = format!("### {heading}\n\n```text\n");
    if let Some((_, group)) = section.group
        && let Some(description) = &group.description
    {
        write!(out, "{}\n\n", description.get_ref()).unwrap();
    }
    for repo in &section.repos {
        out.push_str(&header_line(*repo, locked(*repo)));
        out.push('\n');
    }
    out.push_str("```\n\n");
    out
}

/// `[<id> @ <ref> <sha7>] <description>. Packages: <p>, <p>. Start: <path>, <path>.`
/// with every empty field left out.
fn header_line(repo: RepoRef, locked: &LockedRepo) -> String {
    let (git_ref, sha7) = (locked.pin.display_ref(), locked.pin.short_id());
    // a SHA ref would only repeat the commit id
    let at = if is_full_sha(git_ref, sha7) {
        sha7.to_string()
    } else {
        format!("{git_ref} {sha7}")
    };
    let mut line = format!("[{} @ {at}]", repo.id);
    if let Some(description) = &repo.repo.description {
        let description = description.get_ref();
        write!(
            line,
            " {}.",
            description.strip_suffix('.').unwrap_or(description)
        )
        .unwrap();
    }
    let list = |label: &str, items: &[toml::Spanned<String>]| {
        let items: Vec<&str> = items.iter().map(|i| i.get_ref().as_str()).collect();
        (!items.is_empty()).then(|| format!(" {label}: {}.", items.join(", ")))
    };
    line.extend(list("Packages", &repo.repo.packages));
    line.extend(list("Start", &repo.repo.start));
    line
}

/// Whether `git_ref` is a full commit id (a ref that is 40 hex characters) of the commit
/// that starts with `sha7`.
fn is_full_sha(git_ref: &str, sha7: &str) -> bool {
    is_commit_id(git_ref) && git_ref.starts_with(sha7)
}
