name: ci
on:
  push:
    branches: [prod]
jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-26.04, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v2
      - run: scripts/check
        shell: bash
